# Generated by Django 4.1 on 2022-12-01 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Peluqueria', '0002_turno_alter_turnos_fecha_deseada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fecha_deseada',
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='fecha_deseada',
        ),
    ]
