# Generated by Django 4.1 on 2022-12-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peluqueria', '0004_rename_clientes_cliente_delete_turnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('producto', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
